### ISSUE TITLE
Add compatibility with other mods

### ISSUE THREAD

**Issue by hea3ven** [hea3ven/BuildingBricks#20]
Mods with decorative blocks:
- [x] Thaumcraft

**Comment by kreezxil** [comment]
I'm glad you caught this one, I have had to remove your mod because of this compatibility issue which occurs at worldgen time.

**Comment by hea3ven** [comment]
No, this is about adding other mod's decorative blocks as materials for the trowel. I'm not aware of any issues with worldgen. I did fix a big memory issue at worldgen in version 1.0.2, did you try that version?

**Comment by kreezxil** [comment]
When did you put out 1.0.2?

In my mod pack the Extreme 1.8 Mega Mod Pack, when you create a new world, it hangs, the console shows your mod and thaumcraft battling it out over some kind issue. However, it hangs and doesn't officially crash so there is no fml log. I can force the issue and copy the console if you want that.

**Comment by hea3ven** [comment]
> When did you put out 1.0.2?

In October I think, latest version is 1.0.3.
If you can get me the log, I'd appreciate it. You can find the console log in the "logs" folder as "logs/fml-client-latest.log" or "logs/fml-server-latest.log".

**Comment by kreezxil** [comment]
i know where it is, ... look for it soon

**Comment by kreezxil** [comment]
Well, darn it, I can't reproduce it, it must've been caused by another bugged out mod that I removed, because no matter your mod is not inhibiting new worldgen, so for this issue you can consider my input essential moot.

Until next time. :)

Keep up the good work! :1234:
