### ISSUE TITLE
Add ability to disable block by types in config

### ISSUE THREAD

**Issue by InkDragon** [hea3ven/BuildingBricks#27]
Would love to have the option to toggle off some block types in the config. I would like to use this mod with another that adds similar features(stairs, slabs, vertical slabs) and this option would prevent duplicate blocks.

**Comment by hea3ven** [comment]
If you are talkin about the mod "The Little Things" I'll have to create a compatibility module, because if you just disable a block type, the trowel won't automatically pick up the other mod's blocks.

**Comment by InkDragon** [comment]
yup that's the mod, and I understand that. I'd be fine with this for a quick fix until the compatibility module is done.

**Comment by hea3ven** [comment]
3608fd9
