### ISSUE TITLE
Issues: Bricks turn into different wall types

### ISSUE THREAD

**Issue by kwpugh** [hea3ven/BuildingBricks#29]
Issue on my server.

Sandstone bricks don't craft into sandstone walls, but rather, into cracked stone brick walls

others as well, like cracked stone bricks become mycelium walls with black/purple no texture 

Let me know what info you might need, if any, to look into this.

**Comment by hea3ven** [comment]
Make sure the client config is the same as the server, specifically the file "conf/BuildingBricks/material_ids.nbt"

**Comment by kwpugh** [comment]
Indeed, copied the file from the server to the client and all is well.   Thank you.

Very nice mod, by the way

**Comment by hea3ven** [comment]
No problem, next version will warn about it if the files are different when a client connects.
