### ISSUE TITLE
My game crash with WAILA and half slab? (Not understand it...)

### ISSUE THREAD

**Issue by Sasikaa** [hea3ven/BuildingBricks#30]
Here is my crashlog:

http://pastebin.com/EhQ1yRD7

**Comment by hea3ven** [comment]
Is it with any half slab, or only with grass slabs? It might be a grass half slab that replaced the bottom half of a 2 block "tall grass" block, in which case it would be a bug in waila: https://bitbucket.org/ProfMobius/waila/issues/242/issue-if-double-high-flower-missing-part .
