### ISSUE TITLE
Crash on Server startup

### ISSUE THREAD

**Issue by rckymtnrfc** [hea3ven/BuildingBricks#33]
I'm seeing a crash when starting the server with Building Bricks 1.3.0.  

http://pastebin.com/RwvNmgqB

Client starts up fine, fyi.

**Comment by mengy007** [comment]
I'm getting the same crash. I'm not certain but I think it's line 51 in the file ModBuildingBricksCompatVanilla.java. You may need a client/server proxy to only get that in on the client side.

**Comment by hea3ven** [comment]
Fixed in version 1.3.1, thanks for the report.
