### ISSUE TITLE
Grass slabs not dropping

### ISSUE THREAD

**Issue by rckymtnrfc** [hea3ven/BuildingBricks#41]
When breaking grass slabs there are no drops.  Using BuildingBricks-1.8.9-1.4.3.  

Thanks!

**Comment by rckymtnrfc** [comment]
Just broke a grass slab and I got the following crash on the server.

http://pastebin.com/uG9MKicg

**Comment by hea3ven** [comment]
I can't reproduce, can you post the server log?

**Comment by rckymtnrfc** [comment]
Here is the server log with the event when I break the grass slab.  http://pastebin.com/MFkGrUbs

**Comment by rckymtnrfc** [comment]
Since you can't reproduce it, I thought I'd remove some mods and see if I can find out what might be conflicting.  Running just Forge 1764 and Building Bricks 1.4.3 and I still don't get any drops for the grass slabs.

The SSP log looks to be the same as the server but here it is if you wanted to see it.  http://pastebin.com/SUrVTAqz

**Comment by rckymtnrfc** [comment]
Tested with Forge 1794, same result.

**Comment by hea3ven** [comment]
Actually, the log when the server starts would be useful.

**Comment by rckymtnrfc** [comment]
Here is the fml-server-latest.log.  It was too large Pastebin.

https://drive.google.com/file/d/0Bx3Y_-bo0ApCYnZvMWczVWV3bms/view?usp=sharing

**Comment by hea3ven** [comment]
Oh, I see the problem, you have the generateBlocks config option off, right? The problem is that it's trying to drop a dirt slab, but the block doesn't exist. I need to disable grass slabs too when generateBlocks is turned off.

**Comment by rckymtnrfc** [comment]
Is it possible to make all blocks not generate except the grass slabs?  I really like the grass slabs in the world gen but I have the other blocks disabled because they are duplicated in another mod I'm using.

**Comment by hea3ven** [comment]
Alright, I just made it not crash when you break a grass slab, and it won't drop an item unless you use silktouch.
