### ISSUE TITLE
JsonSyntaxException with clean config folder BuildingBricks 1.4.5

### ISSUE THREAD

**Issue by LlubNek** [hea3ven/BuildingBricks#44]
Crash report:
http://pastebin.com/qgd4eFaQ

Game output:
http://pastebin.com/B7AKvria

I removed most of my mods and deleted the config folder when I first got this crash in case this was a mod interaction bug, but it's still happening.  Might still blame Quark...

**Comment by hea3ven** [comment]
#BlameVazkii :) https://github.com/Vazkii/Quark/pull/3

**Comment by hea3ven** [comment]
Fixed in Quark-beta-7
