### ISSUE TITLE
Missing Recipe for Material Bag

### ISSUE THREAD

**Issue by efgi** [hea3ven/BuildingBricks#49]
There is no listed recipe for the material bag and I can't even access it through Just Enough Items.

**Comment by hea3ven** [comment]
Well, this is awkward ...

**Comment by efgi** [comment]
What's the recipe supposed to be? I can at least check if it's working correctly.

**Comment by hea3ven** [comment]
I doubt it would work considering I have forgotten to event think what the recipe could be :P, hence the awkwardness.

**Comment by efgi** [comment]
Perhaps like a chest made of wool? It's a lot of inventory space, so that seems about right for cost. Or if you want to bring the cost down it could follow the bucket, minecart, or cauldron recipe. Then assign it the same way you do a trowel?

Leather could be a good material as well.

**Comment by hea3ven** [comment]
I'm thinking of making it out of reed. Although you can probably not tell from the crappy icon, the material bag icon is supposed to be like a sandbag, which is made of jute fiber, and I guess the reed is the closest thing in vanilla. Plus I think it will be safer, to prevent recipe conflicts.

**Comment by efgi** [comment]
Well in any case, I look forward to having it fully implemented. I love the mod so far, even if it does clutter the inventory a bit.
