### ISSUE TITLE
Problem in combination with journey map mc 1.9 forge 1865

### ISSUE THREAD

**Issue by Jiraiyah** [hea3ven/BuildingBricks#50]
Hi, as soon as i add your mod to the mods folder and try to load mc from launcher without any java args, i get this : 

NOW: Better Sprinting:1.1.4a, Building Bricks Vanilla Compat:1.9-1.4.8, Building Bricks:1.9-1.4.8, Chameleon:1.9-2.1.3, ChickenChunks:2.0.1.26, CodeChicken Core:2.0.1.53, Ender Utilities:0.5.1, Forge Mod Loader:8.0.99.99, Iron Chest:6.0.132.776, JourneyMap:1.9-5.1.6b2, Just Enough Items:3.2.11.186, Minecraft Coder Pack:9.19, Minecraft Forge:12.16.0.1865, Realistic Terrain Generation:1.9-0.0.5, Storage Drawers:1.9-3.1.6, Village Info:1.0.0, Waila:1.7.0
[15:51:52] [Client thread/ERROR] [journeymap]: Could not load blocksTexture :java.lang.OutOfMemoryError: Java heap space
[15:51:52] [Client thread/WARN] [journeymap]: BlocksTexture not yet loaded

and mc becomes unresponsive, not sure if this issue is related to your mod or it's from journey map side but i know it starts as soon as i add your mod to the list

**Comment by techbrew-mc** [comment]
OOMs **on startup** just mean you haven't allocated enough memory for all the mods to work properly, including resource/texture packs.  Neither BB or JM or any other mod in your list are necessarily behaving badly.  JM just logs OOM errors to make it easier for people to diagnose the problem.

This is the equivalent of putting more things in your grocery cart than you can pay for.  You either remove stuff until you can pay for what remains, or you need more money.  In this case, you need to allocate more memory, or remove mods.  Google "allocate more memory to Minecraft launcher" and you'll be all set.

**Comment by hea3ven** [comment]
I looked a bit into it and there's nothing I can optimize. I'm doing the rendering "the vanilla way", and it means there is a lot of models that take up a lot of memory.
