### ISSUE TITLE
Grassslab worldgen issue

### ISSUE THREAD

**Issue by cauliflower69** [hea3ven/BuildingBricks#57]
Server closed after some players explored

http://pastebin.com/aku16hvC

**Comment by RealGrep** [comment]
Seems like it might be related to the crash I just encountered in the nether. I can no longer log in.

The log: http://pastebin.com/rP0XZtjm

Forge version 1891, BuildingBricks-1.9-1.4.8.jar.

I reckon I'll be in lava if I get this working again so I can log in. heh

Let me know if I can provide any other information.

**Comment by hea3ven** [comment]
@cauliflower69 from what I've read, that kind of error can be caused when the server does not have enough cpu to handle the worldgen, does the log contain lines like "Can't keep up! Did the system time change, or is the server overloaded? Running Xms behind, skipping Y tick(s)"?

**Comment by cauliflower69** [comment]
Thank for the reply

**Comment by hea3ven** [comment]
I did realize, after @RealGrep comment, that the worldgen does run on the nether and end, even though they don't actually do anything. So I'm gonna filter those dimensions out, which might alleviate a little bit the server.

**Comment by hea3ven** [comment]
@cauliflower69 If you don't mind, could you test if you get the errors when using forge version 12.16.0.1884 or previous

**Comment by hea3ven** [comment]
Oh, looks like it might be a forge bug https://github.com/MinecraftForge/MinecraftForge/issues/2837, try updating to the latest forge version.
