### ISSUE TITLE
Crash on startup: could not detect the running version

### ISSUE THREAD

**Issue by Darkhax** [hea3ven/BuildingBricks#60]
I get [this](https://gist.github.com/darkhax/8fcd49f0aff612d1df4e671d78955e80) crash during the launch of the game.

**Comment by hea3ven** [comment]
Are you using some kind of custom launcher/minecraft jar? this is a really weird crash, unfortunately I'm eating the exception that would tell me exactly what went wrong.

**Comment by hea3ven** [comment]
Can you try with the new version 1.9-2.0.2?

**Comment by Darkhax** [comment]
Hello, sorry for not responding sooner. This crash was caused when using the BTM launcher. I believe the launcher is a fork of MCUpdater. After I wiped my entire instance and redownloaded the files the issue went away and I have not been able to reproduce since.

**Comment by hea3ven** [comment]
Nice
