### ISSUE TITLE
Crash game when starting, version BuildingBricks-1.9.4-2.0.3

### ISSUE THREAD

**Issue by BPanter** [hea3ven/BuildingBricks#65]
[crash-2016-05-24_20.27.36-client.txt](https://github.com/hea3ven/BuildingBricks/files/279846/crash-2016-05-24_20.27.36-client.txt)

**Comment by hea3ven** [comment]
Are you using the default config, or did you change something?

**Comment by BPanter** [comment]
What do you mean? List of installed mods below. 

forge-1.9.4-12.17.0.1917
BuildingBricks-1.9.4-2.0.3
OptiFine_1.9.4_HD_U_B4

No more mods installed.

**Comment by hea3ven** [comment]
Try with the new version, 2.0.4.

**Comment by BPanter** [comment]
Unfortunately, the same error.

[crash-2016-05-27_11.18.22-client.txt](https://github.com/hea3ven/BuildingBricks/files/285837/crash-2016-05-27_11.18.22-client.txt)

**Comment by BPanter** [comment]
Have tested version BuildingBricks-1.9.4-2.0.5
The bug is still present. 

[crash-2016-06-08_03.48.57-client.txt](https://github.com/hea3ven/BuildingBricks/files/304150/crash-2016-06-08_03.48.57-client.txt)
