### ISSUE TITLE
Catched unhandled exception : [class com.hea3ven.buildingbricks.core.tileentity.TileMaterial] java.lang.NullPointerException

### ISSUE THREAD

**Issue by 0Navis0** [hea3ven/BuildingBricks#66]
I already posted this issue on curseforge, but I'm not sure if it had been seen. I get a serious problem with the 1.9 and 1.94 version of building bricks when I destroy some blocks of the mod. Minecraft totally freezes and I get this error.

[03:17:54] [Netty Server IO #1/WARN]: Catched unhandled exception : [class com.hea3ven.buildingbricks.core.tileentity.TileMaterial] java.lang.NullPointerException

Then I'm obliged to force Minecraft to stop, and if I wait too long, Windows tells me that Minecraft doesn't answer more and stop the program by itself without any crash report.

When I restart the world, all the blocks in the world from building bricks are displayed with a missing texture, I can travel them like if they didn't exist, and when I look them with Waila, it displays tile.invalidMaterialBlock.name. If I try to interact with these blocks again, minecraft freezes again with the same error. When the world loads too, I get these errors as much as there are building bricks blocks on the world.
[16:02:46] [Client thread/ERROR]: Could not load the material of a block

Curruntly for what I tried, it happens with any blocks of glass and ice, it doesn't seem happen with the wool, dirt and wood, but I hadn't had the time to try the other blocks, and the bug could happen with many other blocks. But anyway when the bug happens and I restart and go inside the world, all the blocks, even the ones wich didn't provocate the bug, are touched by the missing texture and the tile.invalidMaterialBlock.name, and when I interact with them freezes minecraft again with the same error.

Please correct this bug, this is a serious and very annoying issue wich make Building Brick totally unusable.

**Comment by hea3ven** [comment]
I assume this is in single player, right?, can you post what it says in the log around the first error?

**Comment by 0Navis0** [comment]
Yeah it's in single player, and it happens in both creative and survival. And what I get after the error is that http://pastebin.com/ysnkg7v2

Edit : I forgot to post the last part of the log :
Minecraft has crashed with the stop code -805306369

**Comment by hea3ven** [comment]
Try with the new version, 2.0.4.

**Comment by 0Navis0** [comment]
It still doesn't work... :(
I get the same problem with the reasonant crystal from deep reasonance https://github.com/McJty/DeepResonance/issues/71
This bug seems to be recurent with all the tile entities used as blocks.

**Comment by 0Navis0** [comment]
I had made a copy of the full log for the deep resonance, but the building bricks bug is the same, so I show you it if it can help you. http://pastebin.com/KhwV1WKg

I noticed that with the new version, when I reload the world after that Minecraft crashed, the block I tried to destroy isn't more here, and the other building blocks are still here and not more displayed with a missing textures, but when I break an ice or glass block, the bug happens again.

**Comment by hea3ven** [comment]
Would you mind testing if the bug happens when you remove optifine?

**Comment by 0Navis0** [comment]
Sadly it doesn't change anything. I think that the problem come from the 1.9 itself. A lot of tile entities of other mods and Minecraft itself are touched by this bug. I will report this bug in the Minecraft issue tracker.

**Comment by Hypsellis** [comment]
I created the issue, you can add additionnal informations if you want since you are a modder and knows surely better how Minecraft works.
https://bugs.mojang.com/browse/MC-102755

**Comment by hea3ven** [comment]
Does it happen when you use forge without mods?, also, you could try with only buildingbricks.

**Comment by 0Navis0** [comment]
Yes it happens only with building bricks installed. The only block I know wich come from Minecraft itself and provocates this bug without any mods and forge is the ender frame. I discovered recently that this bug happened with the blood glass of blood arsenal and the tank of evilcraft, and it's surely only the beginning. I curruntly try all the blocks with provocate this error. Maybe we will be able to understand from where it comes. I will try to create a list of all the blocks touches by this bug. From what I noticed, it happens especially on all transparent tile entities.

**Comment by 0Navis0** [comment]
I curruntly all the blocks one by one of all the mods of my modpack, it will be long, but I will publish a list of all the blocks wich provocates this bug. I will warn all the potential mod owners wich are affected by this bug. It's the best solution for solving this really annoying bug.

**Comment by 0Navis0** [comment]
I close this issue, I moved it here https://github.com/hea3ven/BuildingBricks/issues/69
