### ISSUE TITLE
missing integration of some blocks

### ISSUE THREAD

**Issue by 0Navis0** [hea3ven/BuildingBricks#67]
I post that here too. It miss the integration of some block like the chiseled quartz, the pilliar quartz, the soulsand and the glowstone.

It miss too the biotite and the snow bricks integration from Quartz.

It would be nice if you added for all the aesthetic from Biome O Plenty, Botania, Blood Magic, ActuallyAdditions, RandomThings, TechReborn, EvilCraft, AbyssalCraft blocks. And create a compatibility with More Materials http://minecraft.curseforge.com/projects/more-materials?gameCategorySlug=mc-mods&projectID=226917

**Comment by 0Navis0** [comment]
I repost for requesting an integration for the aesthetic blocks of Substratum, Foundry, Tinker Construct, EnderIO, Blood Arsenal and Chisel in more that the ones I had already told in the last message.
You should prepare too an integration for Thaumcraft, IndustrialCraft, BuildCraft, Forestry, Railcraft, ImmersiveEngineering and Mekanism wich will update them surely soon for the 1.9.4

**Comment by 0Navis0** [comment]
Do you think you will add an integration for all these blocks ?

**Comment by hea3ven** [comment]
I'd like to, yes, eventually. But I've been very busy IRL so I have been focusing on at least providing bugfixes, rather than new features.

**Comment by 0Navis0** [comment]
Yeah I understand, but it would be at least to have a support for all the new blocks added by Quark and missing Vanilla blocks like quartz.

**Comment by jriwanek** [comment]
Quark handles it's own Building bricks integration.

**Comment by 0Navis0** [comment]
Maybe, anyway I had already reported this issue in the Quark repository. https://github.com/Vazkii/Quark/issues/38

**Comment by 0Navis0** [comment]
It would be awesome to add a support for More Materials blocks too. The stained clay walls (including all colours) and brick walls are duplicated with the Building Bricks ones. You should disable them when More Materials is present too.
