### ISSUE TITLE
java.lang.IllegalStateException: TickNextTick list out of synch

### ISSUE THREAD

**Issue by derSchotte** [hea3ven/BuildingBricks#73]
Hi,

MC 1.9.4 / Forge 12.17.0.1954 / BuildingBricks 1.9.4-2.0.4
i try to generate a new world with your mod installed with half slab generation on and i get this crash-log. whitout halfslap generation there is no problem... 

i got the same crash on MC 1.9 / Forge 12.16.1.1934 / BuildingBricks 1.9 2.0.4

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.4.jar)
  CoreMod (Aroma1997Core-1.9.4-1.0.6.0.b65.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 07.06.16 09:20
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:696)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:696)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['derSchotte'/1173, l='New World', x=142,50, y=72,00, z=246,50]]
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 4131512732454491548
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (152,64,252), Chunk: (at 8,4,12 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 6 game time, 6 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 92491 (now: false), thunder time: 52911 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1184205696 bytes (1129 MB) / 2559049728 bytes (2440 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.28 Powered by Forge 12.17.0.1954 18 mods loaded, 18 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1954.jar) 
    UCHIJAAAA   Forge{12.17.0.1954} [Minecraft Forge](forge-1.9.4-12.17.0.1954.jar) 
    UCHIJAAAA   Aroma1997Core{${version}} [Aroma1997Core](Aroma1997Core-1.9.4-1.0.6.0.b65.jar) 
    UCHIJAAAA   buildingbrickshooks{1.9.4-2.0.4} [Building Bricks Hooks](minecraft.jar) 
    UCHIJAAAA   JEI{3.4.3.207} [Just Enough Items](jei_1.9.4-3.4.3.207.jar) 
    UCHIJAAAA   abyssalcraft{1.9.1.6} [AbyssalCraft](AbyssalCraft-1.9.4-1.9.1.6.jar) 
    UCHIJAAAA   actuallyadditions{1.9.4-r40} [Actually Additions](ActuallyAdditions-1.9.4-r40.jar) 
    UCHIJAAAA   additionalbanners{1.2.0.17} [Additional Banners](AdditionalBanners-1.9.4-1.2.0.18.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.6.0.b65} [Aroma1997Core|Helper](Aroma1997Core-1.9.4-1.0.6.0.b65.jar) 
    UCHIJAAAA   AromaBackup{1.0.1.0.b33} [AromaBackup](AromaBackup-1.9.4-1.0.1.0.b33.jar) 
    UCHIJAAAA   AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.9.4-1.0.1.0.b33.jar) 
    UCHIJAAAA   BiomesOPlenty{4.1.0.2025} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2025-universal.jar) 
    UCHIJAAAA   buildingbricks{1.9.4-2.0.4} [Building Bricks](BuildingBricks-1.9.4-2.0.4.jar) 
    UCHIJAAAA   journeymap{1.9.4-5.2.0} [JourneyMap](journeymap-1.9.4-5.2.0-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.5.32} [Just Enough Resources](JustEnoughResources-1.9.4-0.4.5.32.jar) 
    UCHIJAAAA   JET{2.1.32} [JustEnoughTooltips](JustEnoughTooltips-1.9.4-2.1.32.jar) 
    UCHIJAAAA   SimpleUpgrades{2.0.0} [SimpleUpgrades](simpleupgrades-1.9.4-2.0.0-release.jar) 
    Loaded coremods (and transformers): 
LoadingPluginBuildingBricks (BuildingBricks-1.9.4-2.0.4.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
CoreMod (Aroma1997Core-1.9.4-1.0.6.0.b65.jar)

```
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['derSchotte'/1173, l='New World', x=142,50, y=72,00, z=246,50]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'`
```

can you fix the problem pls for both 1.9 and 1.9.4...

thx

**Comment by slidingmike** [comment]
http://pastebin.com/5eZ0wvPY 

Forge 1257, I believe this is the same or related crash.

**Comment by hea3ven** [comment]
Yeah, the same error. It is related to the grass slabs worldgen, but I'm unsure what exactly is causing it.

**Comment by slidingmike** [comment]
Ah. I was able to get a new world going without the crash happening.
However my testers are running into it. I haven't been able to personally
reproduce. Let me know if there's anything we can do to help ya out.

On Fri, Jun 10, 2016 at 11:44 AM, hea3ven notifications@github.com wrote:

> Yeah, the same error. It is related to the grass slabs worldgen, but I'm
> unsure what exactly is causing it.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/hea3ven/BuildingBricks/issues/73#issuecomment-225219110,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJfbnkXbe1PBpRD1149g1hwWd1Ufh1R7ks5qKYZ1gaJpZM4IvpAZ
> .

## 

Michael Wright
ICM Distributing Account Representative
(865) 307-6190
mawright865@gmail.com
