### ISSUE TITLE
Could not load the material of a block

### ISSUE THREAD

**Issue by ckissane** [hea3ven/BuildingBricks#76]
On world reopen the materials aren't loaded and it results in black/purple checkered blocks.

**Comment by ckissane** [comment]
I found a fix:
Insert:
@Override
    public NBTTagCompound getUpdateTag(){
        NBTTagCompound nbt = super.getUpdateTag();

```
    if (materialId != null)
        nbt.setString("material", materialId);
    return nbt;
```

}

In TileMaterial class

**Comment by JCMais** [comment]
I wonder why this is still open since the commit message should have closed the issue.

Github bug?

**Comment by hea3ven** [comment]
It's because the commit wasn't in the HEAD branch.
