### ISSUE TITLE
Game won't even start up with mod loaded with 2.0.5

### ISSUE THREAD

**Issue by boondockArtist** [hea3ven/BuildingBricks#77]
(Probably not the most professional report, sorry for that)
Alright, so trying to add Building Bricks to Unstable 1.9.4, I get a message stating that I'm missing the library files required, despite getting and adding in the files that the log stated that it required in the right folder. [http://pastebin.com/D8tMNGG1](url) Here's the log.

**Comment by hea3ven** [comment]
Did you add any other of my mods?
