### ISSUE TITLE
Add compatibility with Quark's greener grass tweak

### ISSUE THREAD

**Issue by patrickclank9** [hea3ven/BuildingBricks#78]
Currently grass slabs look like this in the world with the tweak on: 
![2016-06-15_17 14 07](https://cloud.githubusercontent.com/assets/5445944/16101683/f72c5798-331c-11e6-835d-f46a2e5976a9.png)

**Comment by hea3ven** [comment]
I believe it should work if you change buildingbrickscompatvanilla:grass_slab for buildingbricks:grass_slab in quark's config file.

**Comment by patrickclank9** [comment]
That did in fact work. Along with the step, corners, ect.
