### ISSUE TITLE
Client Crash, Placing Andesite Slab

### ISSUE THREAD

**Issue by slidingmike** [hea3ven/BuildingBricks#84]
http://pastebin.com/BKnRZCxm

Forge 1976
MC 1.9.4
BuildingBricks 2.0.9

**Comment by slidingmike** [comment]
User reported that she hard crashes when andesite is slabbed aimed vertically. She was trying to place horizontally.

**Comment by derSchotte** [comment]
Same for me, tryd to place an oak wood slab on Jack'o'Lantern

https://paste.ee/p/KZg3h

**Comment by yepidoodles** [comment]
Another slab crash report for ya

http://www.codesend.com/view/7761fac83e64b53e194faa74f1b99162/

MC version 1.10.2
