### ISSUE TITLE
crash while loading Minecraft

### ISSUE THREAD

**Issue by 0Navis0** [hea3ven/BuildingBricks#95]
I get this crash when I load the game http://pastebin.com/dkDvJUw0

**Comment by WenXin20** [comment]
I got the same, it happens with the newest Tinker's Construct version (2.5.3)
[Crash Report](http://pastebin.com/FaAVHatP)

**Comment by brisingraerowing** [comment]
I just cross-referenced this issue on TConstruct's issues page, as I think this may be a bug with that mod.

**Comment by bonii-xx** [comment]
..why are you trying to load TiCs material jsons in building bricks, though? Those are outside your domain.

**Comment by BSKCorp** [comment]
Can also verify the same issue when loading client or server. http://pastebin.com/8XuGwDBh

**Comment by Terpo** [comment]
Same issue with the new version of Immersive Engineering (0.10 - 43)
http://pastebin.com/DBBMnJYH

**Comment by brisingraerowing** [comment]
I went ahead and changed the line that threw the exception to log it instead, which fixed that crash, but revealed another in TConstruct (which is already fixed in the repo). I don't think crashing is the right thing to do there.

**Comment by hea3ven** [comment]
I'll look into making a cheap fix during the weekend, to at least fix it for now.

**Comment by bonii-xx** [comment]
TiC 2.5.5 also contains a crash fix. So once you release a version that doesn't crash on JSON it can't load we should be fine, since both mods will simply load all files they're interested in but ignore the ones that it can't deal with.

**Comment by hea3ven** [comment]
BuildingBricks 2.0.13 fixes the crash, still need to properly fix the issue, but this will work for now.
