### ISSUE TITLE
Slabs not breaking

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [hea3ven/BuildingBricks#96]
For some unknown reason all slabs added by this mod are behaving as if their made of bedrock, i.e. I can't break them, at all.  Traditional Minecraft slabs are not affected.  I using BuildingBricks-1.10.2-2.0.12 (and yes, I need you to fix the 1.10 version, I've got a lot of mods and it will be a while before they're all updated to 1.11).

**Comment by hea3ven** [comment]
I couldn't reproduce this, please reopen if it's still happening.
